server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://eureka2:7002/eureka,http://eureka1:7001/eureka
    # register-with-eureka: false

spring:
  application:
    name: consumer